name: xai
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - captum
  - dalex=1.5
  - shap=0.41
  - pip:
    - onnx==1.12.0
    - onnx-tf==1.10.0
    - onnxruntime==1.12.1
    - onnxruntime-gpu==1.12.1
    - quantus==0.0.1
    - scikit-explain==0.0.7
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.9.1
    - tensorflow-estimator==2.9.0
    - tensorflow-probability==0.17.0
    - tf2onnx==1.12.1