name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - bottleneck
  - conda
  - conda-merge
  - conda-pack
  - dask
  # - ibis-framework
  - ipykernel
  - ipywidgets
  - mamba
  - modin-all
  - numba
  - numpy
  - pandas
  - pip=22.2.2
  - polars
  - pyarrow
  - pylint
  - pytest
  - pytest-cov
  - python<3.11
  - pyyaml
  - ruff
  - tqdm
  - xarray
  - zarr
  - pip:
    - apprise
    - drawdata
    - fugue[dask,duckdb,ibis,polars]
    - gdown
    - hypothesis
    - ptpython
    - weave