name: cml
channels:
  - rapidsai
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - cudatoolkit=11.6.0
  - cudf
  - cuml
  - dask
  - dask-cuda
  - dask-cudf
  - gputil
  - h5netcdf
  - h5py
  - kmodes
  - netCDF4
  - opencv
  - openpyxl
  - pygments
  - pytorch
  - pytorch-lightning
  - scikit-image
  - scikit-learn
  - scipy
  - torchaudio
  - torchinfo
  - torchvision
  - pip:
    - bentoml
    - deepchecks[vision]
    - great_expectations
    - ivy-core
    - merlin-dataloader
    - nebullvm
    - safetensors
    - segmentation-models
    - torchviz
    - truss