name: nlp
channels:
  - conda-forge
  - defaults
dependencies:
  - gensim
  - langchain
  - pip
  - poppler
  - spacy
  - spacy-model-en_core_web_sm
  - spacy-model-en_core_web_trf
  - textblob
  - transformers
  - pip:
    - deepchecks[nlp]
    - embedchain
    - ludwig
    - nltk
    - pdf2image
    - pillow
    - polyglot
    - pytesseract
    - sentencepiece
    - sentence-transformers
    - unstructured[local-inference]