name: gis
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy
  - fiona
  - folium
  - gdal
  - geojson
  - geopandas
  # - geopolars
  - keplergl
  - rasterio
  - rioxarray
  - shapely
  - xarray-spatial